### ISSUE TITLE
Update http Error Responses to leverage net/http's Error function

### ISSUE THREAD

**Issue by ncatelli** [ncatelli/mockserver#42]
`net/http` added a helper for error responses that could clean up error handling code in the framework, we should look at updating any error responses to leverage https://golang.org/pkg/net/http/#Error

**Comment by Ravi19967** [comment]
can i look into this ?

**Comment by ncatelli** [comment]
Of course @Ravi19967 I think there is only one occurrence of this https://github.com/ncatelli/mockserver/blob/f2328867be197c5e6fe46676d2dade5b27c1f3f1/pkg/router/handler.go#L63 but I always appreciate the PRs.
